api_platform:
    title: 'BileMo API'
    description: "Cette API permet de récupérer une liste de téléphones mobiles ainsi que le détail d'un téléphone mobile.
      Elle permet également de récupérer les utilisateurs, le détail d un utilisateur, mais aussi ajouter ou supprimer un utilisateur."
    # Enable the FOSUserBundle integration.
    enable_fos_user: false
    # Enable the Nelmio Api doc integration.
    enable_nelmio_api_doc: false
    # Enable the Swagger documentation and export.
    enable_swagger: true
    # Enable Swagger ui.
    enable_swagger_ui: true
    # Enable the entrypoint.
    enable_entrypoint: true
    # Enable the docs.
    enable_docs: true
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
    # The list of enabled formats. The first one will be the default.
    formats:
        jsonld:
            mime_types: ['application/ld+json']

        json:
            mime_types: ['application/json']

        html:
            mime_types: ['text/html']

    # The list of enabled error formats. The first one will be the default.
    error_formats:
        jsonproblem:
            mime_types: ['application/problem+json']

        jsonld:
            mime_types: ['application/ld+json']

framework:
    serializer: { enable_annotations: true }